-- TODO: 
-- This query will return a table with the top 10 revenue categories
-- in English, the number of orders and their total revenue. 
-- It will have different columns:
--      Category, that will contain the top 10 revenue categories;
--      Num_order, with the total amount of orders of each category;
--      Revenue, with the total revenue of each category.

-- HINT: 
-- All orders should have a delivered status and the Category and actual delivery date should be not null.
-- For simplicity, if there are orders with multiple product categories, consider the full order's payment_value in the summation of revenue of each category

WITH category_revenue AS (
    SELECT
        t."product_category_name_english" AS "Category",
        COUNT(DISTINCT o."order_id") AS "Num_order",
        SUM(p."payment_value") AS "Revenue"
    FROM
        olist_orders o
    JOIN
        olist_order_items oi ON o."order_id" = oi."order_id"
    JOIN
        olist_products pr ON oi."product_id" = pr."product_id"
    JOIN
        product_category_name_translation t ON pr."product_category_name" = t."product_category_name"
    JOIN
        olist_order_payments p ON o."order_id" = p."order_id"
    WHERE
        o."order_status" = 'delivered'
        AND o."order_delivered_customer_date" IS NOT NULL
        AND t."product_category_name_english" IS NOT NULL
    GROUP BY
        t."product_category_name_english"
)
SELECT
    "Category",
    "Num_order",
    "Revenue"
FROM
    category_revenue
ORDER BY
    "Revenue" DESC
LIMIT 10;

--### Explanation of the Query:
--1. **Filtering**:
--   - The `WHERE` clause ensures that only orders with `order_status = 'delivered'`, a non-null `order_delivered_customer_date`, and a valid category name in English are included.

--2. **Aggregation**:
--   - `COUNT(DISTINCT o."order_id")` counts the unique orders for each category.
--   - `SUM(p."payment_value")` calculates the total revenue for each category.

--3. **Sorting and Limiting**:
--   - The `ORDER BY "Revenue" DESC` ensures the categories are sorted by revenue in descending order.
--   - `LIMIT 10` restricts the output to the top 10 revenue categories.

--### Output Columns:
--- **Category**: The English name of the product category.
--- **Num_order**: The total number of unique orders for the category.
--- **Revenue**: The total revenue generated by the category.
